In [ ]:
# WEEK2 PYTHON CUNY BRIDGE 07/23/2022 
# Do not use built in programs to do the following.
# Write the programs to demonstrate that you understand the math behind them.  
# Provide all solutions in an .html file. 


In [ ]:
# 1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.
# Sources: https://www.mathsisfun.com/algebra/eigenvalue.html
# Sources: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html
# Using/coding with Numpy makes much more easier to work on. Learning the concept of "eigenvalues and eigenvectors" is another learning curve for me.

In [ ]:
import numpy
a = numpy.array ([[3, 1],[2, 2]])
print ("Initial Array: ",)
print ( a)

w,v = numpy.linalg.eig (a)
print ("Eigenvalues is:", w)
print ("Eigenvectors is:")
print (v)


Initial Array: 
[[3 1]
 [2 2]]
Eigenvalues is: [4. 1.]
Eigenvectors is:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [ ]:
# 2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition
# Sources: https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/
# Sources: https://gregorygundersen.com/blog/2018/12/10/svd/
# Sources: https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

# A = UΣV^t or A = UDV^t or A = USV^h (where A has 'm' rows & 'n' columns )
# vectors u: orthogonal m * m matrix: its columns are left singular vectors
# vectors v: orthogonal n * n matrix: its columns are right singular vectors
# values  d: diagonal   m * n matrix: elements along its diagonal are singular values

In [ ]:
import numpy
a = numpy.array ([[0,0,0,1,1],[2,0,0,1,2],[4,1,0,2,0],[3,1,0,2,0]], dtype = numpy.float32)
print ("Initial Array:")
print (a)

U, s, V = numpy.linalg.svd (a, full_matrices= False)
print("U: 2D arrays of m * m square matrix: ", U , "\n")
print("s: 1D array of singular values: ", s, "\n")
print("V: 2D arrays of n * n square matrix:", V)


Initial Array:
[[0. 0. 0. 1. 1.]
 [2. 0. 0. 1. 2.]
 [4. 1. 0. 2. 0.]
 [3. 1. 0. 2. 0.]]
U: 2D arrays of m * m square matrix:  [[-0.09699973  0.48506695  0.7914053  -0.35913602]
 [-0.38284308  0.787775   -0.44374314  0.18956216]
 [-0.712383   -0.3006906  -0.17906062 -0.6083033 ]
 [-0.58011436 -0.23174514  0.3804036   0.6819491 ]] 

s: 1D array of singular values:  [6.3631787  2.1626036  0.9092391  0.07992283] 

V: 2D arrays of n * n square matrix: [[-8.41648757e-01 -2.03121349e-01  0.00000000e+00 -4.81651992e-01
  -1.35574669e-01]
 [-1.49101675e-01 -2.46201262e-01  0.00000000e+00  9.61667150e-02
   9.52840805e-01]
 [-5.08686781e-01  2.21441194e-01  0.00000000e+00  8.25248480e-01
  -1.05671778e-01]
 [-1.03120625e-01  9.21461046e-01  1.20736754e-15 -2.78797925e-01
   2.50094771e-01]]


In [ ]:
# 3.  Write a Python program to compute the determinant of an array.
# Sources: https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html
# Sources: https://www.mathsisfun.com/algebra/matrix-determinant.html
# Sources: https://www.youtube.com/watch?v=Ip3X9LOh2dk

# det([[a,c],[b,d]]) = ad - bc   (for 2D matrix)

In [ ]:
import numpy
a = numpy.array ([[3, 2],[1, 5]])
print ("Initial Array:")
print (a)

print ("Determinant:")
print (numpy.linalg.det(a))

Initial Array:
[[3 2]
 [1 5]]
Determinant:
13.0
